
import { Article, Tool, Playbook, CryptoGuide } from './types';

export const ADSENSE_PUB_ID = "ca-pub-4722208859927111";
export const CONTACT_EMAIL = "openyourais888@gmail.com";

export const getRandomImageRandom = (category: string) => {
  const AI_IMAGES = [
    "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"
  ];
  const MONEY_IMAGES = [
    "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"
  ];
  return category === 'AI' ? AI_IMAGES[Math.floor(Math.random() * AI_IMAGES.length)] : MONEY_IMAGES[Math.floor(Math.random() * MONEY_IMAGES.length)];
};

export const saveNewArticle = (article: Article): Article[] => {
  const saved = localStorage.getItem('openyourais_new_articles');
  let articles: Article[] = saved ? JSON.parse(saved) : [];
  if (!articles.find(a => a.id === article.id)) {
    articles = [article, ...articles];
    localStorage.setItem('openyourais_new_articles', JSON.stringify(articles));
  }
  return articles;
};

// --- DIRECTORY OF 10 HIGH-VALUE TOOLS ---
export const TOOLS: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT Plus (o1-Preview)',
    category: 'LLM / Reasoning',
    shortDesc: 'The final frontier of computational reasoning with Chain-of-Thought capabilities.',
    fullDesc: 'OpenAI o1 represents a radical shift in transformer architecture. Unlike traditional autoregressive models that generate tokens in milliseconds, o1 utilizes internal "thinking" time through Chain-of-Thought reasoning. This allows the AI to logically validate each step of a solution before presenting it. It is the definitive tool for those seeking process automation that does not tolerate logical errors. Its infrastructure allows for a reduction in hallucinations by up to 80% in purely logical tasks, making it the gold standard for applied enterprise intelligence.',
    priceModel: 'Freemium',
    url: 'https://chat.openai.com',
    features: ['Inference-time Reasoning', 'Advanced Data Analysis', 'DALL-E 3 Visual Gen', 'Custom GPTs'],
    useCases: ['Complex Prompt Engineering', 'Precision Financial Analysis', 'Software Architecture']
  },
  {
    id: '2',
    name: 'Claude 3.5 Sonnet',
    category: 'LLM / Coding',
    shortDesc: 'The preferred model for developers due to its technical precision and Artifacts interface.',
    fullDesc: 'Claude 3.5 Sonnet, developed by Anthropic, set a new productivity benchmark with the launch of "Artifacts." This interface allows code, websites, and documents generated by the AI to be viewed and edited in a dedicated side window. Technically, the model demonstrates superior understanding of linguistic nuances and a coding capability that often outperforms GPT-4o in front-end tests. Its 200k token context window allows for processing entire codebases, making it an indispensable co-pilot for modern developers and micro-SaaS creators.',
    priceModel: 'Freemium',
    url: 'https://claude.ai',
    features: ['Artifacts UI', '200k Token Window', 'High Emotional Intelligence', 'Vision Analysis'],
    useCases: ['Agile Web Development', 'Technical Code Review', 'Long-form Creative Writing']
  },
  {
    id: '3',
    name: 'Midjourney v6.1',
    category: 'Visual / Art',
    shortDesc: 'Leading image generator for photorealism and commercial art direction.',
    fullDesc: 'Midjourney v6.1 is a neural rendering engine that understands cinematic lighting, lens composition, and material textures at a professional level. Version 6.1 introduced significant improvements in hand and text rendering, as well as the "Style Reference" (SREF) feature, which allows a brand to maintain absolute visual consistency across all generations. It has reduced prototyping time from weeks to seconds for design agencies.',
    priceModel: 'Paid',
    url: 'https://midjourney.com',
    features: ['Style Reference (SREF)', 'Character Consistency', 'Ultra-High Res Upscaling', 'Niji Mode for Art'],
    useCases: ['Luxury Branding', 'Game Assets', 'Digital Marketing Campaigns']
  },
  {
    id: '4',
    name: 'Runway Gen-3 Alpha',
    category: 'Video / AI',
    shortDesc: 'Cinematic AI-generated video with realistic physics and lighting.',
    fullDesc: 'Runway continues to lead the generative video revolution with Gen-3 Alpha. This model understands the laws of physics, light, and motion, generating 10-second clips with a temporal consistency that was previously impossible. With "Motion Brush," creators can control exactly which parts of a static image should move, transforming independent content production into a Hollywood-level process.',
    priceModel: 'Paid',
    url: 'https://runwayml.com',
    features: ['Motion Brush', 'Text-to-Video', 'Image-to-Video', 'Director Mode'],
    useCases: ['Short Film Production', 'High-Impact Social Commercials', 'Agile VFX']
  },
  {
    id: '5',
    name: 'ElevenLabs',
    category: 'Audio / Voice',
    shortDesc: 'The pinnacle of vocal synthesis and voice cloning with emotional weight.',
    fullDesc: 'ElevenLabs uses deep neural networks to capture the timbre, intent, and emotion behind human speech. Its "Speech-to-Speech" technology allows recording a narration and converting it into a professional announcer voice in 29 supported languages. It has eliminated the cost barrier to professional dubbing for solo creators.',
    priceModel: 'Freemium',
    url: 'https://elevenlabs.io',
    features: ['Instant Voice Cloning', 'Emotional Inflection Control', 'Multilingual Synthesis', 'Studio Sound'],
    useCases: ['YouTube Channel Automation', 'Video Localization', 'Audiobook Production']
  },
  {
    id: '6',
    name: 'Perplexity AI',
    category: 'Search / Research',
    shortDesc: 'The conversational search engine that cites sources in real-time.',
    fullDesc: 'Perplexity AI delivers synthesized and verified answers by integrating multiple language models. It searches the web in real-time and provides a consolidated response with direct citations. Its "Pro Search" capability allows it to ask follow-up questions to refine the search, acting like a human data analyst filtering internet noise.',
    priceModel: 'Freemium',
    url: 'https://perplexity.ai',
    features: ['Pro Search Mode', 'Citation-based Answers', 'File Upload Analysis', 'Custom Collection Focus'],
    useCases: ['Market Research', 'Fact Checking', 'Technical Report Writing']
  },
  {
    id: '7',
    name: 'Notion AI',
    category: 'Productivity',
    shortDesc: 'Integrated intelligence that organizes and processes your knowledge.',
    fullDesc: 'Notion AI transforms Notion into an active organizational brain. It can read hundreds of pages of notes and extract action plans, summarize long technical documents, and rewrite drafts. The big advantage is its direct integration with your database context, suggesting connections that isolated chat AIs cannot see.',
    priceModel: 'Paid',
    url: 'https://notion.so',
    features: ['Automated Summaries', 'Action Item Extraction', 'Database Automation', 'Tone Transformation'],
    useCases: ['Complex Project Management', 'Corporate Wiki Creation', 'Product Brainstorming']
  },
  {
    id: '8',
    name: 'Jasper AI',
    category: 'Marketing',
    shortDesc: 'Enterprise platform to scale your brand voice.',
    fullDesc: 'Jasper is focused on high-performance enterprise marketing. Its main innovation is the ability to learn and apply "Brand Voice" across all generated content. With integrations for SEO and campaign workflows, Jasper allows teams to produce 10x more content without sacrificing quality.',
    priceModel: 'Paid',
    url: 'https://jasper.ai',
    features: ['Brand Voice Memory', 'Campaign Workflows', 'SEO Mode Integration', 'Art Generator'],
    useCases: ['Content Marketing at Scale', 'E-commerce Copywriting', 'Ads Strategy']
  },
  {
    id: '9',
    name: 'Synthesia',
    category: 'Video / Avatars',
    shortDesc: 'Create professional videos with human avatars without cameras.',
    fullDesc: 'Synthesia allows any company to create videos presented by realistic avatars just by typing a script. Using advanced video synthesis, avatars have perfect lip-sync and natural movements. This is transformative for corporate training where hiring actors would be prohibitive.',
    priceModel: 'Paid',
    url: 'https://synthesia.io',
    features: ['AI Video Avatars', 'Auto-Captions', 'Multi-Language Synthesis', 'Custom Avatar Creation'],
    useCases: ['Training and Onboarding', 'Customer Support Videos', 'Personalized Sales']
  },
  {
    id: '10',
    name: 'Descript',
    category: 'Audio / Video Editing',
    shortDesc: 'Text-based media editing that feels like magic.',
    fullDesc: 'Descript revolutionized editing by treating media like a text document. Removing a word from the transcript removes the corresponding clip from the video. Its "Studio Sound" feature uses AI to remove background noise, making a smartphone microphone sound like a professional studio.',
    priceModel: 'Freemium',
    url: 'https://descript.com',
    features: ['Text-Based Media Editing', 'Studio Sound AI', 'Overdub Voice Clone', 'Automatic Filler Word Removal'],
    useCases: ['Podcasting Editing', 'Social Content Creation', 'Long-form Interviews']
  }
];

// --- MONETIZATION PLAYBOOKS (EXPANDED TO 5) ---
export const PLAYBOOKS: Playbook[] = [
  {
    id: 'p1',
    title: 'High-Ticket YouTube Automation',
    tldr: 'Learn to build digital empires using AI pipelines to dominate high CPM niches.',
    roi: '$5k-$20k/month potential',
    timeline: '90-180 Days',
    difficulty: 'Medium',
    steps: ['High-Liquidity Niche Identification', 'Claude 3.5 Script Engineering', 'Runway/Midjourney Visual Production', 'Video SEO and CTR Strategy', 'Scaling via External Operators'],
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>The New YouTube Paradigm</h2>
      <p>YouTube automation in 2025 is no longer about volume, but about <strong>Authority Quality</strong>. Google's algorithm now prioritizes retention and user satisfaction. This playbook teaches how to use Claude 3.5 to create scripts that educate and Runway Gen-3 to create cinematic visuals that keep the user glued to the screen.</p>
      <h3>Phase 1: High CPM Niches</h3>
      <p>We focus on niches like Financial Technology, AI for Health, and Software Engineering, where advertisers pay fortunes for every thousand views (CPM of $30+). Unlike generic curiosity channels, technical niche channels attract qualified audiences and direct sponsors.</p>
      <h3>Phase 2: Visual Fidelity</h3>
      <p>Using Midjourney for static assets and Runway for b-roll ensures your channel looks like a multi-million dollar production. This perceived value is what allows you to command high-ticket sponsorships early on.</p>
    `
  },
  {
    id: 'p2',
    title: 'AI Micro-SaaS Accelerator',
    tldr: 'Develop and market focused tools that solve real pains using AI APIs.',
    roi: 'Equity & Recurring Revenue',
    timeline: '30-60 Days',
    difficulty: 'Hard',
    steps: ['Specific Problem Validation', 'Google AI Studio API Prototyping', 'Agile Front-end Development', 'Stripe Payment Integration', 'Product Hunt Launch'],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>The Micro-SaaS Gold Rush</h2>
      <p>Small tools that solve specific problems (e.g., an email classifier for real estate agents) are extremely lucrative assets. With Gemini 2.5 Flash, the inference cost is so low that profit margins can exceed 90%.</p>
      <h3>Building the Minimum Viable Product</h3>
      <p>Use Google AI Studio to test your system prompts. Once the logic is sound, wrap it in a clean React interface. The key is to solve one painful problem perfectly rather than ten problems poorly.</p>
      <h3>Market Entry</h3>
      <p>The Product Hunt launch is your primary catalyst. Ensure your landing page is optimized for conversion with clear value propositions and a friction-less onboarding process.</p>
    `
  },
  {
    id: 'p3',
    title: 'Premium AI Copywriting Agency',
    tldr: 'Transform marketing writing into a high-margin industrial process.',
    roi: 'Immediate Returns ($3k-$7k/month)',
    timeline: '15-30 Days',
    difficulty: 'Easy',
    steps: ['Niche Definition (E-commerce or B2B)', 'Exclusive Prompt Library Construction', 'Client Acquisition via LinkedIn', 'Batch Delivery via Jasper/Claude'],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>Scaling Creativity</h2>
      <p>Learn to sell value, not hours. With AI, you can produce the work of 10 junior copywriters alone. The secret lies in "Output Curation" and applying advanced SEO strategies that traditional agencies haven't mastered yet.</p>
      <h3>Authority Building</h3>
      <p>Position yourself as an "AI Content Strategist." Clients aren't paying for the writing; they are paying for the strategic alignment and the speed of execution that only your specialized workflow can provide.</p>
    `
  },
  {
    id: 'p4',
    title: 'AI-Driven Branding Agency',
    tldr: 'Create complete visual identities and brand manuals in hours.',
    roi: 'High Margin per Project',
    timeline: '7-14 Days',
    difficulty: 'Medium',
    steps: ['Conceptual Ideation via GPT-o1', 'Style Generation with Midjourney SREF', 'Vectorization and Finalization', 'Notion-based Brand Manual Generation'],
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>Design at Neural Speed</h2>
      <p>Use Midjourney's style references to create consistent visual concepts. This playbook teaches how to charge $2k+ for branding packages that take less than 5 hours to produce.</p>
      <h3>Workflow Optimization</h3>
      <p>The core of this model is the "Neural Moodboard." By presenting the client with high-fidelity concepts in the first 24 hours, you establish a level of momentum that eliminates traditional design friction.</p>
    `
  },
  {
    id: 'p5',
    title: 'Automated AI Newsletters',
    tldr: 'Build a high-value audience with AI-curated technical news.',
    roi: 'Compound Growth Asset',
    timeline: '6-12 Months',
    difficulty: 'Medium',
    steps: ['Profitable Niche Selection', 'Infrastructure Setup (Beehiiv/Substack)', 'AI Agent News Curatorial Workflow', 'Sponsorship and Affiliate Strategy'],
    image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>The Owned Media Asset</h2>
      <p>Newsletters are the most resilient digital assets. Use research IAs like Perplexity to find the hottest news in your niche and Claude to summarize them in an engaging way.</p>
      <h3>Monetization Strategy</h3>
      <p>Once you hit 1,000 subscribers, the Beehiiv ad network and direct sponsorships become viable. This is a long-term play that builds equity in your personal or brand name.</p>
    `
  }
];

// --- CRYPTO GUIDES (EXPANDED TO 3) ---
export const CRYPTO_GUIDES: CryptoGuide[] = [
  {
    id: 'cg1',
    title: 'Ironclad Security: The Digital Custody Protocol',
    level: 'Beginner',
    summary: 'The definitive guide to shielding your digital assets against cyber attacks and centralized custody failures.',
    content: `
      <h2>1. The Philosophy of Individual Sovereignty</h2>
      <p>In the blockchain ecosystem, the aphorism "Not your keys, not your coins" is fundamental law. If you keep your assets on a centralized exchange (CEX), you own a promise of payment, not the asset itself.</p>
      <h3>2. Anatomy of Wallets: Hot vs Cold</h3>
      <p>Understanding the difference between hot and cold storage is vital for financial survival:</p>
      <ul>
        <li><strong>Hot Wallets (Software):</strong> Apps like MetaMask. Excellent for daily DeFi interactions but permanently connected to the internet.</li>
        <li><strong>Cold Wallets (Hardware):</strong> Devices like Ledger or Trezor. They keep your private keys offline, requiring physical confirmation for transactions.</li>
      </ul>
      <h3>3. The 24-Word Protocol (Seed Phrase)</h3>
      <p>Your Seed Phrase is the master backup of your digital life. Never take a photo of it. Use stainless steel plates for physical recording to protect against fire and floods.</p>
    `
  },
  {
    id: 'cg2',
    title: 'Macro Intelligence: Decoding Market Cycles',
    level: 'Intermediate',
    summary: 'Understand how global liquidity flows and Bitcoin cycles dictate Altcoin performance.',
    content: `
      <h2>1. The Periodicity of Capital</h2>
      <p>Crypto markets move in approximately 4-year cycles, historically dictated by the Bitcoin Halving. Understanding the phase of the cycle is the difference between generational wealth and total liquidation.</p>
      <h3>2. Fundamental On-Chain Indicators</h3>
      <ul>
        <li><strong>MVRV Z-Score:</strong> Identifies when Bitcoin is over or undervalued relative to its "real value."</li>
        <li><strong>BTC Dominance:</strong> When Bitcoin dominance drops, it usually signals the start of "Altseason."</li>
      </ul>
      <h3>3. Market Cycle Psychology</h3>
      <p>Elite investors buy during "Despair" and sell during "Euphoria." The Wall Street Cheat Sheet is an indispensable tool for identifying accumulation vs. distribution phases.</p>
    `
  },
  {
    id: 'cg3',
    title: 'Advanced DeFi: The Yield Engineering Lab',
    level: 'Advanced',
    summary: 'Institutional strategies for passive income through concentrated liquidity and liquid staking.',
    content: `
      <h2>1. The DeFi Ecosystem in 2025</h2>
      <p>Decentralized Finance has evolved into complex financial engineering. You are the bank, providing liquidity and receiving fees in return.</p>
      <h3>2. Concentrated Liquidity (Uniswap V3)</h3>
      <p>Protocols allow providing liquidity in specific price ranges, increasing capital efficiency but introducing the risk of <strong>Impermanent Loss</strong>. Learn to calculate the necessary hedge to neutralize volatility.</p>
      <h3>3. Liquid Staking Derivatives (LSD)</h3>
      <p>Lido and Rocket Pool allow you to stake assets and receive a derivative token (e.g., stETH) to use as collateral, maximizing yield without losing liquidity.</p>
    `
  }
];

// --- INITIAL ARTICLES ---
export const ARTICLES: Article[] = [
  {
    id: 'art-001',
    slug: 'adsense-approval-masterclass-2025',
    title: 'How to Get AdSense Approved in 2025: The Ultimate Authority Guide',
    excerpt: 'Forget the old tricks. Google now demands E-E-A-T and content that solves real problems. Learn how to structure your site for commercial success.',
    content: `
      <h2>1. The End of Thin Content</h2>
      <p>Google AdSense has become extremely rigorous. Publishing short, generic articles no longer guarantees approval. The algorithm now looks for sites that act as <strong>Destination Resources</strong>.</p>
      <h3>2. The E-E-A-T Pillar</h3>
      <p>E-E-A-T stands for Experience, Expertise, Authoritativeness, and Trustworthiness. Demonstrate this through professional bios, links to trusted sources, and technical data.</p>
      <div class="bg-cyber-primary/10 border-l-4 border-cyber-primary p-4 my-6">
        <strong>APPROVAL CHECKLIST:</strong> Minimum of 20-30 long articles, logical navigation, and detailed privacy policies.
      </div>
    `,
    category: 'Monetization',
    tags: ['AdSense', 'SEO', 'Digital Business'],
    date: 'Dec 22, 2025',
    readTime: '20 min',
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 'art-002',
    slug: 'google-ai-studio-gemini-2-5-guide',
    title: 'Google AI Studio: Unlocking Gemini 2.5 Pro Power in Your Workflow',
    excerpt: 'A technical deep-dive into Google’s new AI infrastructure and how it beats the competition in speed and cost.',
    content: `
      <h2>The Next-Gen Laboratory</h2>
      <p>Google AI Studio is an integrated development environment (IDE) for the new era of artificial intelligence. By offering direct access to Gemini 2.5 Pro, Google has democratized massive processing power.</p>
      <h3>Context Window Advantage</h3>
      <p>Gemini 2.5 Pro scales to millions of tokens. This allows uploading entire libraries of documentation or hours of video into a single prompt for cross-referencing.</p>
    `,
    category: 'AI',
    tags: ['Google AI', 'Gemini', 'LLM'],
    date: 'Dec 18, 2025',
    readTime: '15 min',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"
  }
];
