
import { Article, Tool, Playbook, CryptoGuide } from './types';

export const ADSENSE_PUB_ID = "ca-pub-4722208859927111";
export const CONTACT_EMAIL = "openyourais888@gmail.com";

export const getRandomImageRandom = (category: string) => {
  const AI_IMAGES = [
    "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"
  ];
  const MONEY_IMAGES = [
    "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"
  ];
  return category === 'AI' ? AI_IMAGES[Math.floor(Math.random() * AI_IMAGES.length)] : MONEY_IMAGES[Math.floor(Math.random() * MONEY_IMAGES.length)];
};

export const saveNewArticle = (article: Article): Article[] => {
  const saved = localStorage.getItem('openyourais_new_articles');
  let articles: Article[] = saved ? JSON.parse(saved) : [];
  if (!articles.find(a => a.id === article.id)) {
    articles = [article, ...articles];
    localStorage.setItem('openyourais_new_articles', JSON.stringify(articles));
  }
  return articles;
};

// --- DIRECTORY OF 10 HIGH-VALUE TOOLS ---
export const TOOLS: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT Plus (o1-Preview)',
    category: 'LLM / Reasoning',
    shortDesc: 'The final frontier of computational reasoning with Chain-of-Thought capabilities.',
    fullDesc: 'OpenAI o1 represents a radical shift in transformer architecture. Unlike traditional autoregressive models that generate tokens in milliseconds, o1 utilizes internal "thinking" time through Chain-of-Thought reasoning. This allows the AI to logically validate each step of a solution before presenting it. It is the definitive tool for those seeking process automation that does not tolerate logical errors.',
    priceModel: 'Freemium',
    url: 'https://chat.openai.com',
    features: ['Inference-time Reasoning', 'Advanced Data Analysis', 'DALL-E 3 Visual Gen', 'Custom GPTs'],
    useCases: ['Complex Prompt Engineering', 'Precision Financial Analysis', 'Software Architecture']
  },
  {
    id: '2',
    name: 'Claude 3.5 Sonnet',
    category: 'LLM / Coding',
    shortDesc: 'The preferred model for developers due to its technical precision and Artifacts interface.',
    fullDesc: 'Claude 3.5 Sonnet, developed by Anthropic, set a new productivity benchmark with the launch of "Artifacts." This interface allows code, websites, and documents generated by the AI to be viewed and edited in a dedicated side window. Technically, the model demonstrates superior understanding of linguistic nuances and a coding capability that often outperforms competitors.',
    priceModel: 'Freemium',
    url: 'https://claude.ai',
    features: ['Artifacts UI', '200k Token Window', 'High Emotional Intelligence', 'Vision Analysis'],
    useCases: ['Agile Web Development', 'Technical Code Review', 'Long-form Creative Writing']
  },
  {
    id: '3',
    name: 'Midjourney v6.1',
    category: 'Visual / Art',
    shortDesc: 'Leading image generator for photorealism and commercial art direction.',
    fullDesc: 'Midjourney v6.1 is a neural rendering engine that understands cinematic lighting, lens composition, and material textures at a professional level. Version 6.1 introduced significant improvements in hand and text rendering, as well as the "Style Reference" (SREF) feature for brand consistency.',
    priceModel: 'Paid',
    url: 'https://midjourney.com',
    features: ['Style Reference (SREF)', 'Character Consistency', 'Ultra-High Res Upscaling', 'Niji Mode for Art'],
    useCases: ['Luxury Branding', 'Game Assets', 'Digital Marketing Campaigns']
  },
  {
    id: '4',
    name: 'Runway Gen-3 Alpha',
    category: 'Video / AI',
    shortDesc: 'Cinematic AI-generated video with realistic physics and lighting.',
    fullDesc: 'Runway continues to lead the generative video revolution with Gen-3 Alpha. This model understands the laws of physics, light, and motion, generating clips with temporal consistency that was previously impossible in generative workflows.',
    priceModel: 'Paid',
    url: 'https://runwayml.com',
    features: ['Motion Brush', 'Text-to-Video', 'Image-to-Video', 'Director Mode'],
    useCases: ['Short Film Production', 'High-Impact Social Commercials', 'Agile VFX']
  },
  {
    id: '5',
    name: 'ElevenLabs',
    category: 'Audio / Voice',
    shortDesc: 'The pinnacle of vocal synthesis and voice cloning with emotional weight.',
    fullDesc: 'ElevenLabs uses deep neural networks to capture the timbre, intent, and emotion behind human speech. Its technology allows recording a narration and converting it into a professional announcer voice across dozens of supported languages.',
    priceModel: 'Freemium',
    url: 'https://elevenlabs.io',
    features: ['Instant Voice Cloning', 'Emotional Inflection Control', 'Multilingual Synthesis', 'Studio Sound'],
    useCases: ['YouTube Channel Automation', 'Video Localization', 'Audiobook Production']
  },
  {
    id: '6',
    name: 'Perplexity AI',
    category: 'Search / Research',
    shortDesc: 'The conversational search engine that cites sources in real-time.',
    fullDesc: 'Perplexity AI delivers synthesized and verified answers by integrating multiple language models. It searches the web in real-time and provides a consolidated response with direct citations for maximum transparency.',
    priceModel: 'Freemium',
    url: 'https://perplexity.ai',
    features: ['Pro Search Mode', 'Citation-based Answers', 'File Upload Analysis', 'Custom Collection Focus'],
    useCases: ['Market Research', 'Fact Checking', 'Technical Report Writing']
  },
  {
    id: '7',
    name: 'Notion AI',
    category: 'Productivity',
    shortDesc: 'Integrated intelligence that organizes and processes your knowledge.',
    fullDesc: 'Notion AI transforms your workspace into an active organizational brain. It can read hundreds of pages of notes and extract action plans, summarize long technical documents, and rewrite drafts with perfect contextual awareness.',
    priceModel: 'Paid',
    url: 'https://notion.so',
    features: ['Automated Summaries', 'Action Item Extraction', 'Database Automation', 'Tone Transformation'],
    useCases: ['Complex Project Management', 'Corporate Wiki Creation', 'Product Brainstorming']
  },
  {
    id: '8',
    name: 'Jasper AI',
    category: 'Marketing',
    shortDesc: 'Enterprise platform to scale your brand voice.',
    fullDesc: 'Jasper is focused on high-performance enterprise marketing. Its main innovation is the ability to learn and apply a specific brand voice across all generated content, ensuring consistency in large-scale deployments.',
    priceModel: 'Paid',
    url: 'https://jasper.ai',
    features: ['Brand Voice Memory', 'Campaign Workflows', 'SEO Mode Integration', 'Art Generator'],
    useCases: ['Content Marketing at Scale', 'E-commerce Copywriting', 'Ads Strategy']
  },
  {
    id: '9',
    name: 'Synthesia',
    category: 'Video / Avatars',
    shortDesc: 'Create professional videos with human avatars without cameras.',
    fullDesc: 'Synthesia allows users to create videos presented by realistic avatars just by typing a script. Using advanced video synthesis, avatars have perfect lip-sync and natural movements, reducing production costs by up to 90%.',
    priceModel: 'Paid',
    url: 'https://synthesia.io',
    features: ['AI Video Avatars', 'Auto-Captions', 'Multi-Language Synthesis', 'Custom Avatar Creation'],
    useCases: ['Training and Onboarding', 'Customer Support Videos', 'Personalized Sales']
  },
  {
    id: '10',
    name: 'Descript',
    category: 'Audio / Video Editing',
    shortDesc: 'Text-based media editing that feels like magic.',
    fullDesc: 'Descript revolutionized editing by treating media like a text document. Removing a word from the transcript removes the corresponding clip from the video. Its AI features ensure studio-quality sound from any source.',
    priceModel: 'Freemium',
    url: 'https://descript.com',
    features: ['Text-Based Media Editing', 'Studio Sound AI', 'Overdub Voice Clone', 'Automatic Filler Word Removal'],
    useCases: ['Podcasting Editing', 'Social Content Creation', 'Long-form Interviews']
  }
];

// --- MONETIZATION PLAYBOOKS (5 ITEMS) ---
export const PLAYBOOKS: Playbook[] = [
  {
    id: 'p1',
    title: 'High-Ticket YouTube Automation',
    tldr: 'Build digital empires using AI pipelines to dominate high CPM niches.',
    roi: '$5k-$20k/month potential',
    timeline: '90-180 Days',
    difficulty: 'Medium',
    steps: ['High-Liquidity Niche Identification', 'Claude 3.5 Script Engineering', 'Runway/Midjourney Visual Production', 'Video SEO and CTR Strategy', 'Scaling via External Operators'],
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>The New YouTube Paradigm</h2>
      <p>YouTube automation in 2025 is no longer about volume, but about <strong>Authority Quality</strong>. Google's algorithm now prioritizes retention and user satisfaction.</p>
      <h3>Phase 1: High CPM Niches</h3>
      <p>We focus on niches like Financial Technology, AI for Health, and Software Engineering. Technical niche channels attract qualified audiences and command high-ticket sponsorships.</p>
    `
  },
  {
    id: 'p2',
    title: 'AI Micro-SaaS Accelerator',
    tldr: 'Develop and market focused tools that solve real pains using AI APIs.',
    roi: 'Equity & Recurring Revenue',
    timeline: '30-60 Days',
    difficulty: 'Hard',
    steps: ['Specific Problem Validation', 'Google AI Studio API Prototyping', 'Agile Front-end Development', 'Stripe Payment Integration', 'Product Hunt Launch'],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>The Micro-SaaS Gold Rush</h2>
      <p>Small tools that solve specific problems are extremely lucrative. With the Gemini 2.5 Flash API, inference costs are low enough that profit margins can exceed 90%.</p>
      <h3>Building the MVP</h3>
      <p>Use Google AI Studio to test your system prompts. Once the logic is sound, wrap it in a clean React interface. Solve one painful problem perfectly.</p>
    `
  },
  {
    id: 'p3',
    title: 'Premium AI Copywriting Agency',
    tldr: 'Transform marketing writing into a high-margin industrial process.',
    roi: '$3k-$10k/month potential',
    timeline: '15-30 Days',
    difficulty: 'Easy',
    steps: ['B2B Niche Specialization', 'Technical Prompt Stack Setup', 'LinkedIn Authority Outreach', 'Content Management via AI Agents'],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>Scaling High-Performance Content</h2>
      <p>Learn to sell strategic outcomes, not hours. With AI, you can produce the work of 10 junior copywriters alone while maintaining superior quality.</p>
      <h3>The Strategy</h3>
      <p>Position yourself as an AI Content Strategist. Clients aren't paying for the writing; they are paying for the strategic alignment and speed of execution.</p>
    `
  },
  {
    id: 'p4',
    title: 'AI-Driven Branding Factory',
    tldr: 'Create complete visual identities and brand manuals in hours, not weeks.',
    roi: 'High Margin per Project ($2k+)',
    timeline: '7-14 Days',
    difficulty: 'Medium',
    steps: ['Conceptual Ideation with GPT-o1', 'Consistent Asset Generation via MJ SREF', 'Vectorization and UI Prototyping', 'Automated Brand Manual Creation'],
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>Neural Branding Framework</h2>
      <p>The traditional design model is broken. Use Midjourney's style references to create consistent visual concepts at scale and command professional agency rates.</p>
    `
  },
  {
    id: 'p5',
    title: 'Automated AI Intel Newsletters',
    tldr: 'Build high-value owned audiences with AI-curated technical news streams.',
    roi: 'Passive Income & Equity Building',
    timeline: '180+ Days',
    difficulty: 'Medium',
    steps: ['High-Value Tech Niche selection', 'Beehiiv Infrastructure Setup', 'AI News Curation Agent Workflow', 'Growth via Multi-Channel Distro'],
    image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=800&q=80",
    content: `
      <h2>The Asset of Owned Media</h2>
      <p>Direct access to an audience is the most resilient digital asset. Use AI agents to scan research papers and summarize them for a technical audience.</p>
    `
  }
];

// --- CRYPTO GUIDES (3 ITEMS) ---
export const CRYPTO_GUIDES: CryptoGuide[] = [
  {
    id: 'cg1',
    title: 'Ironclad Security: The Digital Custody Protocol',
    level: 'Beginner',
    summary: 'The definitive guide to shielding your digital assets against cyber attacks.',
    content: `
      <h2>Not Your Keys, Not Your Coins</h2>
      <p>In the decentralized economy, self-custody is the fundamental law. Keeping assets on an exchange is a risk that most vanguard investors are no longer willing to take.</p>
      <h3>Hardware Wallet Strategy</h3>
      <p>Hardware wallets isolate your private keys from the internet. This protocol details how to set up, secure, and back up a physical cold storage device.</p>
    `
  },
  {
    id: 'cg2',
    title: 'Macro Intelligence: Decoding Market Cycles',
    level: 'Intermediate',
    summary: 'Understand global liquidity flows and Bitcoin periodicity.',
    content: `
      <h2>The Periodicity of Capital</h2>
      <p>Cryptocurrency markets move in cycles historically dictated by the Bitcoin Halving. Understanding these phases is critical for long-term capital preservation.</p>
      <h3>Key Indicators</h3>
      <p>Mastering the MVRV Z-Score and Bitcoin Dominance allows you to identify accumulation vs. distribution zones with high statistical probability.</p>
    `
  },
  {
    id: 'cg3',
    title: 'Advanced DeFi: The Yield Engineering Lab',
    level: 'Advanced',
    summary: 'Institutional-grade strategies for maximizing capital efficiency.',
    content: `
      <h2>Yield Maximization</h2>
      <p>Advanced DeFi is about the recursive use of capital. Learn to leverage liquid staking derivatives (LSDs) and concentrated liquidity pools to generate institutional yields.</p>
    `
  }
];

// --- INITIAL ARTICLES ---
export const ARTICLES: Article[] = [
  {
    id: 'art-001',
    slug: 'adsense-approval-masterclass-2025',
    title: 'How to Get AdSense Approved in 2025: The Ultimate Authority Guide',
    excerpt: 'Forget the old tricks. Google now demands E-E-A-T and content that solves real problems. Learn how to structure your site for commercial success.',
    content: 'Full technical guide on AdSense approval protocols...',
    category: 'Monetization',
    tags: ['AdSense', 'SEO', 'Business'],
    date: 'Dec 22, 2025',
    readTime: '20 min',
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 'art-002',
    slug: 'unlock-the-future-a-deep-dive-into-google-ai-studio',
    title: 'Unlock the Future: A Deep Dive into Google AI Studio',
    excerpt: 'Mastering the Gemini architecture via Google AI Studio is the highest-leverage skill for the next decade.',
    content: 'In-depth analysis of Google AI Studio features and capabilities...',
    category: 'AI',
    tags: ['Google AI', 'Gemini', 'Automation'],
    date: 'Dec 18, 2025',
    readTime: '15 min',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"
  }
];
