
export type Category = 'AI' | 'Crypto' | 'Monetization' | 'AI Sales' | 'AI Business' | 'AI Security' | 'AI Architecture' | 'Business Intelligence' | 'Tutorial' | 'AI News';

export interface Article {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string; // HTML string or markdown
  category: Category;
  tags?: string[];
  date?: string;
  readTime: string;
  image?: string; // URL placeholder
  imageUrl?: string; // Alternative image field
  author?: string;
  featured?: boolean;
  isAutoGenerated?: boolean;
  publishDate?: string; // Alternative date field
}

export interface Tool {
  id: string;
  name: string;
  category: string;
  shortDesc: string;
  fullDesc: string;
  priceModel: 'Free' | 'Freemium' | 'Paid';
  url: string;
  features: string[];
  useCases: string[];
}

export interface Playbook {
  id: string;
  title: string;
  tldr: string;
  roi: string;
  timeline: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  steps: string[];
  content?: string; // HTML Content
  image?: string;
}

export interface CryptoGuide {
  id: string;
  title: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  summary: string;
  content: string;
}
