import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { Card, SectionTitle } from '../components/Components';
import { GoogleGenAI } from "@google/genai";
import { saveNewArticle, getRandomImageRandom } from '../constants';
import { Article } from '../types';
import { Lock, LogIn, Sparkles, Save, LogOut, CheckCircle, Copy, Trash2, FileText } from 'lucide-react';

export const AdminPage: React.FC = () => {
  const { isAuthenticated, login, logout } = useAuth();
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [topic, setTopic] = useState('');
  const [generating, setGenerating] = useState(false);
  const [generatedArticle, setGeneratedArticle] = useState<Article | null>(null);
  const [localArticles, setLocalArticles] = useState<Article[]>([]);

  useEffect(() => {
    const saved = localStorage.getItem('openyourais_new_articles');
    if (saved) {
      try { setLocalArticles(JSON.parse(saved)); } catch (e) {}
    }
  }, []);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!login(password)) setError('Invalid Access Key');
  };

  const handleGenerate = async () => {
    if (!topic) return;
    setGenerating(true);
    setError('');

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      
      const systemPrompt = `
        You are a Master Technical Writer for "Open Your AIs". 
        Your mission is to produce a 1.500+ word "Pillar Article" that is functionally indistinguishable from high-end professional journalism.

        CRITICAL AD-SENSE COMPLIANCE RULES:
        1. CONTENT DEPTH: Each H2 section must contain 400-500 words of dense analysis. No fluff.
        2. RICH ELEMENTS: You MUST include at least one HTML <table> comparing options OR a detailed 5-question FAQ section with long answers.
        3. E-E-A-T: Mention real-world 2025 market trends, regulatory frameworks, and economic impact.
        4. TONE: Authoritative, objective, and deeply educational.

        STRUCTURE:
        - H1 Title (SEO Optimized)
        - Executive Summary (300 words)
        - 6 H2 Sections (Technical Deep Dives)
        - H3 sub-headings for hierarchy
        - "The Investor's Perspective" or "Future Roadmap" section
        - Conclusion

        RESPONSE FORMAT:
        Use ONLY these custom delimiters exactly:
        [[TITLE]] title [[CATEGORY]] AI/Crypto/Monetization [[EXCERPT]] description [[TAGS]] tag1, tag2 [[READTIME]] 15 min [[CONTENT]] <html>...</html>
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-3-pro-preview',
        contents: `Research and write a massive 1,500-word authoritative guide on: ${topic}. Focus on 2025 metrics and actionable wealth strategies.`,
        config: {
          systemInstruction: systemPrompt,
          tools: [{googleSearch: {}}],
          thinkingConfig: { thinkingBudget: 15000 } // Max thinking for max word count
        }
      });

      const rawText = response.text || '';
      const getSection = (tag: string) => {
        const parts = rawText.split(`[[${tag}]]`);
        if (parts.length < 2) return '';
        return parts[1].split('[[')[0].trim();
      };

      const title = getSection('TITLE');
      const categoryRaw = getSection('CATEGORY');
      const excerpt = getSection('EXCERPT');
      const tagsRaw = getSection('TAGS');
      const readTime = getSection('READTIME');
      const content = getSection('CONTENT');

      let category: any = 'AI';
      if (categoryRaw.toLowerCase().includes('crypto')) category = 'Crypto';
      if (categoryRaw.toLowerCase().includes('money') || categoryRaw.toLowerCase().includes('monetiz')) category = 'Monetization';

      const newArticle: Article = {
        id: `auto-${Date.now()}`,
        slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        title,
        excerpt,
        content,
        category,
        tags: tagsRaw.split(',').map(t => t.trim()),
        date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
        readTime: readTime || '15 min',
        image: getRandomImageRandom(category),
        isAutoGenerated: true
      };

      setGeneratedArticle(newArticle);
      const existingSaved = JSON.parse(localStorage.getItem('openyourais_new_articles') || '[]');
      const updated = [newArticle, ...existingSaved];
      localStorage.setItem('openyourais_new_articles', JSON.stringify(updated));
      setLocalArticles(updated);

    } catch (err: any) {
      setError(`Generation failed: ${err.message}`);
    } finally {
      setGenerating(false);
    }
  };

  const handlePublish = () => {
    if (generatedArticle) {
      saveNewArticle(generatedArticle);
      setGeneratedArticle(null);
      alert('Article published locally!');
    }
  };

  if (!isAuthenticated) {
    return (
      <div className="container mx-auto px-4 py-20 flex justify-center">
        <Card className="w-full max-w-md p-8 border-cyber-primary/50">
          <h2 className="text-2xl font-bold text-center text-white mb-6">Admin Access</h2>
          <form onSubmit={handleLogin} className="space-y-4">
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Access Key" className="w-full bg-black/50 border border-gray-700 rounded-lg p-3 text-white focus:border-cyber-primary outline-none" />
            <button type="submit" className="w-full bg-cyber-primary text-cyber-bg font-bold py-3 rounded-lg flex items-center justify-center gap-2"><LogIn className="w-5 h-5" /> Login</button>
          </form>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex justify-between items-center mb-8">
        <SectionTitle title="Content Factory" subtitle="Pillar-style articles for Google AdSense compliance." />
        <button onClick={logout} className="text-red-400 flex items-center gap-2"><LogOut className="w-4 h-4" /> Logout</button>
      </div>

      <div className="grid lg:grid-cols-2 gap-8 mb-12">
        <Card className="border-cyber-primary/30">
          <div className="flex items-center gap-2 mb-6 text-cyber-primary"><Sparkles className="w-6 h-6" /><h3 className="text-xl font-bold">Pillar Content Generator</h3></div>
          <div className="space-y-4">
            <input type="text" value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Topic for deep-dive (e.g. The Future of RWA Tokenization)" className="w-full bg-black/40 border border-gray-600 rounded-lg p-3 text-white outline-none focus:border-cyber-primary" />
            <button onClick={handleGenerate} disabled={generating || !topic} className="w-full py-4 rounded-lg font-bold bg-gradient-to-r from-cyber-primary to-cyber-secondary text-white disabled:opacity-50">
              {generating ? "Researching & Writing (~1-2 mins)..." : "Generate Pillar Article"}
            </button>
            {error && <p className="text-red-500 text-sm">{error}</p>}
          </div>
        </Card>

        <Card className={generatedArticle ? 'border-cyber-success/50' : 'border-gray-800'}>
          {generatedArticle ? (
            <div className="flex flex-col h-full">
              <div className="bg-cyber-success/10 text-cyber-success px-4 py-2 rounded mb-4 text-sm flex items-center gap-2"><CheckCircle className="w-4 h-4" /> Pillar Article Ready (Long Form)</div>
              <div className="bg-black/40 p-4 rounded-lg flex-grow overflow-y-auto max-h-[400px] mb-4 prose prose-invert prose-sm" dangerouslySetInnerHTML={{ __html: generatedArticle.content }} />
              <button onClick={handlePublish} className="w-full py-3 bg-cyber-success text-black font-bold rounded-lg flex items-center justify-center gap-2"><Save className="w-4 h-4" /> Publish to Blog</button>
            </div>
          ) : (
            <div className="h-full flex items-center justify-center text-gray-600 min-h-[300px]">Preview will appear after generation.</div>
          )}
        </Card>
      </div>

      {localArticles.length > 0 && (
        <div className="mt-12">
          <h3 className="text-2xl font-bold text-white mb-6 flex items-center gap-2"><FileText className="text-cyber-secondary" /> Local Drafts</h3>
          <div className="grid gap-4">
            {localArticles.map((article) => (
              <div key={article.id} className="bg-white/5 border border-white/10 p-4 rounded-lg flex justify-between items-center">
                <div><h4 className="font-bold text-white">{article.title}</h4><p className="text-xs text-gray-400">{article.date} • {Math.round(article.content.length / 6)} estimated words</p></div>
                <button onClick={() => { navigator.clipboard.writeText(JSON.stringify(article, null, 2)); alert('Copied!'); }} className="px-4 py-2 bg-cyber-primary/20 text-cyber-primary rounded hover:bg-cyber-primary hover:text-black transition-colors flex items-center gap-2"><Copy className="w-4 h-4" /> JSON</button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};